# Generated by Django 5.2.14 on 2026-05-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costline',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='input_mode',
            field=models.CharField(choices=[('ca_total', 'Je fournis le CA'), ('pv_volume', 'Je fournis PV et volumes')], default='pv_volume', max_length=20),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='method',
            field=models.CharField(choices=[('center_analysis', "Centres d'analyse"), ('direct_costing', 'Direct costing'), ('direct_costing_advanced', 'Direct costing évolué')], default='direct_costing', max_length=50),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='preset',
            field=models.CharField(choices=[('small_business', 'Petite entreprise'), ('factory', 'Usine'), ('distribution', 'Distribution')], default='small_business', max_length=20),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='use_reciprocal_allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='use_seasonality',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='costs.costscenario')),
            ],
        ),
        migrations.AddField(
            model_name='costline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='costs.product'),
        ),
    ]
