# Generated by Django 5.2.14 on 2026-05-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costscenario',
            name='method',
            field=models.CharField(choices=[('direct_costing', 'Direct Costing'), ('center_analysis', 'Center Analysis')], default='direct_costing', max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='costs.costscenario')),
            ],
        ),
        migrations.AddField(
            model_name='costline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='costs.product'),
        ),
    ]
