# Generated by Django 5.2.14 on 2026-05-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_costline_is_product_costscenario_input_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Rent', 'Loyer'), ('Salary', 'Salaires'), ('Depreciation', 'Amortissement'), ('Other', 'Autre')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_common', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costs.product')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='costs.costscenario')),
            ],
        ),
        migrations.CreateModel(
            name='VariableCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Material', 'Matériel'), ('Labor', 'Main-d’œuvre'), ('Overhead', 'Frais généraux')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costs.product')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_costs', to='costs.costscenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='costs.costscenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scenario', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality', to='costs.costscenario')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('scenario', 'month')},
            },
        ),
    ]
