# Generated by assistant to support modular UI/UX scenario settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0002_costscenario_method_product_costline_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="costscenario",
            name="input_mode",
            field=models.CharField(
                choices=[("ca_total", "Je fournis le CA"), ("pv_volume", "Je fournis PV et volumes")],
                default="pv_volume",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="costscenario",
            name="preset",
            field=models.CharField(
                choices=[("small_business", "Petite entreprise"), ("factory", "Usine"), ("distribution", "Distribution")],
                default="small_business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="costscenario",
            name="ui_mode",
            field=models.CharField(
                choices=[("simple", "Simple"), ("expert", "Expert")],
                default="simple",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="costscenario",
            name="use_reciprocal_allocation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="costscenario",
            name="use_seasonality",
            field=models.BooleanField(default=False),
        ),
    ]
