# Generated by Django 5.2.14 on 2026-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_costscenario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costscenario',
            name='preset',
            field=models.CharField(blank=True, choices=[('small_business', 'Petite entreprise'), ('factory', 'Usine'), ('distribution', 'Distribution')], max_length=20, null=True),
        ),
    ]
