# Generated by Django 5.2.14 on 2026-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_alter_costscenario_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costscenario',
            name='preset',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('small_business', 'Petite entreprise'), ('factory', 'Usine'), ('distribution', 'Distribution')], max_length=20, null=True),
        ),
    ]
