# Generated by Django 5.2.14 on 2026-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_alter_costscenario_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_final',
            field=models.IntegerField(default=0, verbose_name='Stock final visé'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_initial',
            field=models.IntegerField(default=0, verbose_name='Stock initial'),
        ),
    ]
