# Generated by Django 5.2.14 on 2026-05-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_restore_costline_is_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costscenario',
            name='method',
            field=models.CharField(choices=[('center_analysis', "Centres d'analyse"), ('direct_costing', 'Direct costing'), ('direct_costing_advanced', 'Direct costing évolué')], default='direct_costing', max_length=50),
        ),
        migrations.CreateModel(
            name='VariableCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Material', 'Matériel'), ('Labor', 'Main-d’œuvre'), ('Overhead', 'Frais généraux')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costs.product')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_costs', to='costs.costscenario')),
            ],
        ),
    ]
