# Generated by Django 5.2.14 on 2026-06-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_alter_costscenario_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='total_units',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nombre total d'unités d'œuvre du centre", max_digits=14),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='unit_of_work',
            field=models.CharField(blank=True, help_text="Ex: heure machine, heure main d'œuvre, kg produit", max_length=100),
        ),
        migrations.AlterField(
            model_name='variablecost',
            name='category',
            field=models.CharField(choices=[('Material', 'Matériel'), ('Labor', "Main-d'œuvre"), ('Overhead', 'Frais généraux')], max_length=50),
        ),
        migrations.CreateModel(
            name='CostCenterAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de répartition (ex: 30.00 pour 30%)', max_digits=5)),
                ('from_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_out', to='costs.costcenter')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='costs.costscenario')),
                ('to_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_in', to='costs.costcenter')),
            ],
            options={
                'unique_together': {('from_center', 'to_center')},
            },
        ),
        migrations.CreateModel(
            name='ProductCenterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_used', models.DecimalField(decimal_places=2, default=0, help_text="Nombre d'unités d'œuvre consommées par ce produit", max_digits=14)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='costs.costcenter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_usages', to='costs.product')),
            ],
            options={
                'unique_together': {('product', 'center')},
            },
        ),
    ]
