# Generated by Django 5.2.14 on 2026-05-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_alter_costscenario_method_variablecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Rent', 'Loyer'), ('Salary', 'Salaires'), ('Depreciation', 'Amortissement'), ('Other', 'Autre')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_common', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costs.product')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='costs.costscenario')),
            ],
        ),
    ]
