# Generated by Django 5.2.14 on 2026-05-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0008_fixedcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality', to='costs.costscenario')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('scenario', 'month')},
            },
        ),
    ]
