# Generated by Django 5.2.14 on 2026-06-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_product_stock_final_product_stock_initial'),
        ('costs', '0008_alter_product_name'),
    ]

    operations = [
    ]
