# Generated by Django 5.2.14 on 2026-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_merge_20260605_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variablecost',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
