# Generated by Django 5.2.14 on 2026-05-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_seasonality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='costs.costscenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scenario', 'version_number')},
            },
        ),
    ]
